IgnitionCtrl_Init.h
uint32_t g_PulseCounter
volatile uint32_t g_uSCounter
void IgnitionCtrl_v_Init(void)
Initialization function .
@params none none
References tst_GlobalData::CalculationState, Clock_v_Init, en_InitFinished, GlobalDataValues, GPIO_v_Init, Timer_v_Init.
void Timer_v_Init(void)
Initialization of Timer for microseconds Counter .
@params none none
References HW_Timer_v_Init.
Referenced by IgnitionCtrl_v_Init.
void GPIO_v_Init(void)
Initialization of GPIO registers and Interrupt for input/output Pins .
@params none none
References HW_GPIO_v_Init.
Referenced by IgnitionCtrl_v_Init.
void Clock_v_Init(void)
Initialization of clock .
@params none none
Referenced by IgnitionCtrl_v_Init.
void Data_v_Init(void)
Initialization of global data and set of its states to default values .
@params none none
References tst_GlobalData::AdvanceAngle, tst_GlobalData::CalculationState, en_FiringStateInit, en_InitState, tst_GlobalData::FiringState, tst_GlobalData::FiringTimeCyl_1, tst_GlobalData::FiringTimeCyl_2, GlobalDataValues, tst_GlobalData::IsSynchronised, tst_GlobalData::Microseconds, tst_GlobalData::RPM, tst_GlobalData::TimeElapsedSinceDetection.