IgnitionCtrl_HW_Wrapper.c
volatile uint32_t g_usSinceDetection
Referenced by Firing_v_Cylinder2, HW_Timer_v_Init, TIM2_IRQHandler.
volatile uint32_t g_uSCounter
Referenced by HW_Timer_v_Init, TIM2_IRQHandler.
volatile uint32_t g_uSDebouncingSignalCounter
Referenced by HW_Timer_v_Init, TIM2_IRQHandler.
void HW_GPIO_v_Init(void)
Initialization of GPIO registers and Interrupt for input/output Pins .
@params none none
Referenced by GPIO_v_Init.
void HW_Timer_v_Init(void)
Initialization of Timer for microseconds Counter .
@params none none
References g_uSCounter, g_uSDebouncingSignalCounter, g_usSinceDetection.
Referenced by Timer_v_Init.
void HW_FiringPin_v_Cylinder_1_Set(void)
Firing Pin for Cylinder 1 set to HIGH .
@params none none
References LD4_Pin.
Referenced by Firing_v_Cylinder1.
void HW_FiringPin_v_Cylinder_1_Reset(void)
Firing Pin for Cylinder 1 set to LOW .
@params none none
References LD4_Pin.
Referenced by Firing_v_Cylinder1.
void HW_FiringPin_v_Cylinder_2_Set(void)
Firing Pin for Cylinder 2 set to HIGH .
@params none none
References LD5_Pin.
Referenced by Firing_v_Cylinder2.
void HW_FiringPin_v_Cylinder_2_Reset(void)
Firing Pin for Cylinder 2 set to LOW .
@params none none
References LD5_Pin.
Referenced by Firing_v_Cylinder2.