
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(TOOLCHAIN_PREFIX arm-none-eabi-)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Compilers
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++)

#  --- Find the compilers
find_program(ARM_GCC NAMES ${TOOLCHAIN_PREFIX}gcc REQUIRED)
find_program(ARM_OBJCOPY NAMES ${TOOLCHAIN_PREFIX}objcopy REQUIRED)
find_program(ARM_SIZE NAMES ${TOOLCHAIN_PREFIX}size REQUIRED)

# Tool locations
get_filename_component(COMPILER_DIR  "${ARM_GCC}" DIRECTORY) 
get_filename_component(TOOLCHAIN_DIR "${COMPILER_DIR}" DIRECTORY)

set(CMAKE_OBJCOPY "${ARM_OBJCOPY}")
set(CMAKE_SIZE_UTIL "${ARM_SIZE}")

# Root path for finding libs/includes
set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)